---
# SIYRCEL https://github.com/bossjones/hollywood-vagrant/blob/master/Vagrantfile

- name: "Install hollywood tools"
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - apg.3-dev
      - atop
      - bmon
      - ccze
      - cmatrix
      - dnstop
      - errno
      - ethstatus
      - glances
      - htop
      - ifstat
      - iotop
      - iptotal
      - iptraf-ng
      - itop
      - jnettop
      - jp2a
      - kerneltop
      - latencytop
      - logtop
      - netmrg
      - nload
      - nmon
      - ntop
      - powertop
      - sagan
      - slurm
      - snetz
      - speedometer
      - tiptop
      - top
      - tree
      - vnstat
      - smem
      - bzip2
      - unzip
      - xz-utils
      - wget
      - bzip2
      - libglib2.0-0
      - libxext6
      - libsm6
      - libxrender1
      - hollywood
      # - byobu
      # https://www.cyberciti.biz/python-tutorials/monitor-linux-cpu-temperature-frequency-power-in-a-graphical-way/
      - stress
      # FIXME: FIND THIS!!!!!!!!!!!!!!!! - https://www.tecmint.com/colourised-disk-space-usage-in-linux/
      # - discus


# https://www.cyberciti.biz/python-tutorials/monitor-linux-cpu-temperature-frequency-power-in-a-graphical-way/
- name: Install s-tui
  pip:
    name: "s-tui"


# $ sudo add-apt-repository ppa:amanusk/python-s-tui
# $ sudo apt-get update
# $ sudo apt-get install python-s-tui

# https://github.com/sharkdp/bat
- name: 'install bat - A cat(1) clone with wings.'
  shell: |
    curl -L 'https://github.com/sharkdp/bat/releases/download/v0.9.0/bat_0.9.0_amd64.deb' > /usr/local/src/bat_0.9.0_amd64.deb
    apt install -y /usr/local/src/bat_0.9.0_amd64.deb
  become: yes
  become_method: sudo
  args:
    executable: /bin/bash
    creates: /usr/bin/bat

# https://github.com/sharkdp/bat/releases/download/v0.9.0/bat_0.9.0_amd64.deb
