---
- include_tasks: facts.yml

- include: "{{task| default('tools')}}.yml"

- include_tasks: "kube.yml"
  when: boss__tools__install_kube_tools is defined and boss__tools__install_kube_tools

- include_tasks: "docker.yml"
  when: boss__tools__install_docker_tools is defined and boss__tools__install_docker_tools

- include_tasks: "rust.yml"
  when: boss__tools__install_rust_tools is defined and boss__tools__install_rust_tools

- include_tasks: "glances.yml"
  when: boss__tools__install_glances_tools is defined and boss__tools__install_glances_tools
