---
- name: check if /usr/local/bin/cargo exists
  stat:
    path: /usr/local/bin/cargo
  register: cargo_result
  failed_when: false
  changed_when: false
  tags:
    - slow

- name: "RUST: curl -sSf https://static.rust-lang.org/rustup.sh | sh ONLY if it is not installed already"
  shell: |
    bash -lc "curl -sSf https://static.rust-lang.org/rustup.sh | sh"
  args:
    executable: /bin/bash
  when: not cargo_result.stat.exists
  tags:
    - slow
