---
# https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
- name: install metasploit
  shell: |
    curl 'https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb' > msfinstall
    chmod 755 msfinstall
    ./msfinstall
    touch /tmp/msfinstall
  become: '{{ item }}'
  args:
    executable: /bin/bash
    creates: '/tmp/msfinstall'
  with_items:
    - true  # Run as root


# curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
#   chmod 755 msfinstall && \
#   ./msfinstall
