---
# handlers file for boss-ansible-role-nfs


- name: Run exportfs to export or unexport all directories
  shell: exportfs -ra
  ignore_errors: yes


- name: Restart nfs-kernel-server
  service:
    name: nfs-kernel-server
    state: restarted

- name: kubectl completion bash > /etc/bash_completion.d/kubectl
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl

- name: helm completion bash > /etc/bash_completion.d/helm
  shell: helm completion bash > /etc/bash_completion.d/helm

- name: kubeadm completion bash > /etc/bash_completion.d/kubeadm
  shell: kubeadm completion bash > /etc/bash_completion.d/kubeadm

- name: "curl -L 'https://raw.githubusercontent.com/johanhaleby/kubetail/master/completion/kubetail.bash' > /etc/bash_completion.d/kubetail"
  shell: curl -L 'https://raw.githubusercontent.com/johanhaleby/kubetail/master/completion/kubetail.bash' > /etc/bash_completion.d/kubetail

- name: stern --completion=bash > /etc/bash_completion.d/stern
  shell: stern --completion=bash > /etc/bash_completion.d/stern
